[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "Expense-Tracker-CLI"
version = "0.1.0"
dependencies = ["tabulate>=0.9.0"]

[project.scripts]
expense-tracker = "src.expense_tracker.__main__:main"

[tool.setuptools.packages.find]
where = ["."]